# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "wander" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "ABCDEF" } %>
  pool:   <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB_DEV") { "sagat_ai_development" } %>
  cable:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB_DEV") { "sagat_ai_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB_TEST") { "sagat_ai_test" } %>
  cable:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB_TEST") { "sagat_ai_test" } %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB_PROD") { "sagat_ai_production" } %>
  cable:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB_PROD") { "sagat_ai_production" } %>
